// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5577.GearsBot.subsystems;

import org.usfirst.frc5577.GearsBot.RobotMap;
import edu.wpi.first.wpilibj.*;
import com.ctre.phoenix.motorcontrol.*;

import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class Climber extends Subsystem {

    public Climber() {
    }
    
    public void initDefaultCommand() {

    }
   
    public void moveArm(double velocity){
//    	RobotMap.talonSRX5.set(ControlMode.PercentOutput, velocity);
    }
    
    public void upElevator(double speed){	
//    	RobotMap.talonSRX5.set(ControlMode.PercentOutput, speed); 
    }
    
    public void downElevator(double speed){
//    	RobotMap.talonSRX5.set(ControlMode.PercentOutput, -speed);
    }
    
    public void stop(){
//    	RobotMap.talonSRX5.set(ControlMode.PercentOutput, 0); 
    }


}
